ecommerce/demo/urls.py
from django.urls import path

from . import views

app_name = "demo"

urlpatterns = [
    path("", views.home, name="home"),
    path("categories/", views.category, name="category"),
    path(
        "product-by-category/<slug:category>/",
        views.product_by_category,
        name="product_by_category",
    ),
    path("<slug:slug>", views.product_detail, name="product_detail"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("demo/", include("ecommerce.demo.urls", namespace="demo")),
]

ecommerce/demo/models.py
from django.db import models

# Create your models here.

ecommerce/demo/views.py
from django.contrib.postgres.aggregates import ArrayAgg
from django.db.models import Count
from django.shortcuts import render

from ecommerce.inventory import models


# Create your views here.
def home(request):
    return render(request, "index.html")


def category(request):
    data = models.Category.objects.all()
    # print(models.Category.objects.all().query)
    return render(request, "categories.html", {"data": data})


def product_by_category(request, category):
    data = models.Product.objects.filter(category__name=category).values(
        "id", "name", "slug", "category__name", "product__store_price"
    )
    # print(category)
    # print(data)
    return render(request, "product_by_category.html", {"data": data})


def product_detail(request, slug):
    filter_arguments = []
    if request.GET:
        for value in request.GET.values():
            filter_arguments.append(value)
        # print(filter_arguments)

        data = (
            models.ProductInventory.objects.filter(product__slug=slug)
            .filter(attribute_values__attribute_value__in=filter_arguments)
            .annotate(num_tags=Count("attribute_values"))
            .filter(num_tags=len(filter_arguments))
            .values(
                "id",
                "sku",
                "product__name",
                "store_price",
                "product_inventory__units",
            )
            .annotate(field_a=ArrayAgg("attribute_values__attribute_value"))
            .get()
        )
    else:
        data = (
            models.ProductInventory.objects.filter(product__slug=slug)
            .filter(is_default=True)
            .values(
                "id",
                "sku",
                "product__name",
                "store_price",
                "product_inventory__units",
            )
            .annotate(field_a=ArrayAgg("attribute_values__attribute_value"))
            .get()
        )
        # print(data)

    y = (
        models.ProductInventory.objects.filter(product__slug=slug)
        .distinct()
        .values(
            "attribute_values__product_attribute__name",
            "attribute_values__attribute_value",
        )
    )
    z = (
        models.ProductTypeAttribute.objects.filter(
            product_type__product_type__product__slug=slug
        )
        .values("product_attribute__name")
        .distinct()
    )
    # print(data)
    # print(z)
    # print(y)
    return render(
        request, "product_detail.html", {"data": data, "y": y, "z": z}
    )

ecommerce/demo/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.1.slim.js" integrity="sha256-tXm+sa1uzsbFnbXt8GJqsgi2Tw+m4BLGDof6eUPjbtk=" crossorigin="anonymous"></script>
    <title>Bootstrap demo</title>
  </head>
  <body>
    {% block content %}{% endblock content %}
    
  </body>
</html>

ecommerce/demo/templates/categories.html
{% extends 'base.html' %}
{% block content %}
<h1> Categories</h1>
    {% for x in data %}
        <a href="{% url 'demo:product_by_category' category=x.slug %}"> {{ x.name }}  </a>
        <br>
    {% endfor %}
{% endblock content %}

ecommerce/demo/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1> Home Page </h1>
    <ul>
        <li> <a href="categories/"> Categories </a> </li>
      </ul>
{% endblock content %}

ecommerce/demo/templates/product_by_category.html
{% extends 'base.html' %}
{% block content %}
    <ul>
        {% for x in data  %}
            <li> {{ x.name }} [ <a href="{% url 'demo:product_detail' slug=x.slug %}"> view </a> ]</li>
            <li> {{x.id}}</li>
            <li> Category name: {{x.category__name}}</li>
            <li>Price Kshs: {{x.product__store_price}}</li>
        {% endfor %}
    </ul>
{% endblock content %}

ecommerce/demo/templates/product_detail.html
{% extends 'base.html' %}

{% block content %}
Product detail
<ul>
    <li> {{data.product__name}}</li>
    <li>{{data.sku}}</li>
    <li>{{data.product_inventory__units}}</li>
</ul>

<ul>
    {% for x in z  %}
    <li>
        {{x.product_attribute__name}}
        <ul>
            {% for a in y  %}
            {% if a.attribute_values__product_attribute__name == x.product_attribute__name  %}
            {% if a.attribute_values__attribute_value in data.field_a %}
            <li>
                <div id='target-{{a.attribute_values__attribute_value}}' data-attribute='{{x.product_attribute__name}}'
                    value='{{a.attribute_values__attribute_value}}' class='selected fw-bold'>
                    {{ a.attribute_values__attribute_value }}
                </div>

            </li>
            {% else %}
            <li>
                <div id='target-{{a.attribute_values__attribute_value}}' data-attribute='{{x.product_attribute__name}}'
                    value='{{a.attribute_values__attribute_value}}'>
                    {{ a.attribute_values__attribute_value }}
                </div>


            </li>
            {% endif %}
            {% endif %}
            {% endfor %}
        </ul>
    </li>
    {% endfor %}
</ul>
<script>
    var d = {}
    let textBoxes = document.querySelectorAll('[id^=target]');

    let e = 0
    let f = textBoxes.length

    for (let i in textBoxes) {
        if (e < f) {
            if (textBoxes[i].classList.contains("selected")) {
                d[textBoxes[i].getAttribute('data-attribute')] = textBoxes[i].getAttribute('value')
            }
        } else {
            break
        }
        e++
    }


    {% comment %} document.addEventListener('click', function (e) {
        let value = e.target.getAttribute('value');
        d[e.target.getAttribute('data-attribute')] = e.target.getAttribute('value')
        let querystring = buildUrlWithParams(d)
        let url = window.location.href.split('?')[0]
        window.location.href = url + "?" + querystring;
    }, false); {% endcomment %}

    $('[id^=target]').click(function () {
        const value = this.getAttribute('value');
        d[this.getAttribute('data-attribute')] = this.getAttribute('value')
        const querystring = buildUrlWithParams(d)
        const url = window.location.href.split('?')[0]
        window.location.href = url + "?" + querystring;
    }); 

    function buildUrlWithParams(data) {
        var searchparams = [];
        for (var d in data)
          searchparams.push(d + '=' + data[d]);
        return searchparams.join('&');
      }
</script>
{% endblock content %}